# Generated by Django 2.1.7 on 2019-03-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodle', '0005_auto_20190319_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='deals/'),
        ),
    ]
