# Generated by Django 2.1.7 on 2019-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodle', '0006_auto_20190320_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitmodel',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submitmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
