language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - dev
before_script:
  - cd foodle/front-end
  - npm install -g @angular/cli
  - npm install --save-dev @angular-devkit/build-angular
  - ng update @angular/cli @angular/core
  - npm install bootstrap
  - ng add @angular/material




script:
- ng lint
- ng build --prod --base-href https://github.com/glasgowm148/foodle