language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - dev
before_script:
  - cd Foodle/front-end
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://github.com/glasgowm148/foodle