language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - dev
before_script:
  - cd foodle/front-end
  - npm install 
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://github.com/glasgowm148/foodle